""" Methods related to fussing with a catalog"""
from astropy.table.table import QTable
import numpy as np

from astropy.coordinates import Angle, SkyCoord
from astropy.table import Column, MaskedColumn, Table, hstack, vstack, join
from astropy import units
from frb.galaxies.defs import valid_filters

# Magnitudes outside of [0, MAX_VALID_MAG] are treated as bad photometry.
# 35 is beyond the depth of even the deepest HST and JWST imaging.
MAX_VALID_MAG = 35.


def clean_heasarc(catalog: Table) -> None:
    """
    Insure RA/DEC are ra/dec in the Table

    Table is modified in place

    Args:
        catalog (astropy.table.Table): Catalog generated by astroquery

    Returns:
        None: ``catalog`` is modified in place.

    """
    # RA/DEC
    catalog.rename_column("RA", "ra")
    catalog.rename_column("DEC", "dec")
    for key in ['ra', 'dec']:
        catalog[key].unit = units.deg


def _is_numeric_column(column: Column) -> bool:
    """
    Check whether an astropy column stores numeric values.

    Args:
        column (astropy.table.Column): Column to inspect.

    Returns:
        bool: True if the column has a numeric dtype, False otherwise.

    """
    dtype = getattr(column, 'dtype', None)
    return dtype is not None and np.issubdtype(dtype, np.number)


def _column_values(column: Column) -> np.ndarray:
    """
    Get the values of a (possibly masked) numeric column as floats.

    Args:
        column (astropy.table.Column): Numeric column.

    Returns:
        numpy.ndarray: The values as floats, with masked entries set to NaN.

    """
    return np.ma.filled(np.ma.asarray(column).astype(float), np.nan)


def _photom_key_pairs(pdict: dict) -> dict[str, str | None]:
    """
    Map photometric columns to paired error columns using renamed keys.

    Coordinates, redshifts, flags, IDs, and other non-photometric keys are
    excluded.

    Args:
        pdict (dict): Maps the desired (FRB) column names to the original
            catalog column names; only the keys (the desired names) are used.

    Returns:
        dict: Maps each photometric column name to the name of its
        ``<name>_err`` column, or to None if ``pdict`` has no such error key.

    """
    photom_pairs = {}
    excluded_exact = {'ra', 'dec', 'ebv', 'photo_z', 'photo_z_err', 'z'}
    excluded_prefixes = ('z_spec',)
    excluded_tokens = ('class', 'type', 'flag', 'survey', 'brick', 'tile',
                       'field', 'ellipticity', 'radius', 'area', 'extendedness')
    for key in pdict.keys():
        if key in excluded_exact or key.endswith('_ID'):
            continue
        if key.endswith('_err'):
            continue
        if key.startswith(excluded_prefixes):
            continue
        if any(token in key for token in excluded_tokens):
            continue
        err_key = f'{key}_err'
        photom_pairs[key] = err_key if err_key in pdict else None
    return photom_pairs


def _mask_bad_photometry(catalog: Table, pdict: dict,
                         fill_mask: int | float = -99.0) -> Table:
    """
    Mask bad photometry and paired errors, then fill with sentinel.

    A magnitude is bad if it is non-finite, negative or greater than
    ``MAX_VALID_MAG`` (35).
    An error is bad if it is non-finite, zero, negative or greater than 5.
    Bad magnitudes and bad errors are replaced by ``fill_mask``, as are the
    errors paired with bad magnitudes. The table is modified in place.

    Args:
        catalog (astropy.table.Table): Catalog whose columns have already
            been renamed to the FRB survey names.
        pdict (dict): Maps the desired (FRB) column names to the original
            catalog column names. Used to identify the photometric columns
            and their paired ``_err`` columns.
        fill_mask (int or float, optional): Sentinel value written in place
            of bad entries.

    Returns:
        astropy.table.Table: The catalog with bad photometry replaced by
        ``fill_mask``. Returned unchanged if it is empty or has no
        photometric columns.

    """
    if len(catalog) == 0:
        return catalog

    photom_pairs = _photom_key_pairs(pdict)
    if not photom_pairs:
        return catalog

    # Loop over photometric keys and mask bad values along with their paired errors
    for phot_key, err_key in photom_pairs.items():

        # Skip if photometric key is missing or non-numeric
        if phot_key not in catalog.colnames:
            continue
        if not _is_numeric_column(catalog[phot_key]):
            continue
        
        # Masked, non-finite, negative, or unphysically large photometric values.
        # Masked entries are treated as NaN so that they are flagged regardless
        # of the (arbitrary) data stored underneath the mask.
        phot_values = _column_values(catalog[phot_key])
        phot_bad = ~np.isfinite(phot_values)

        # This is key. MAX_VALID_MAG is deeper than any survey we use, including HST and JWST,
        #   while still catching the placeholder values (e.g. 98, 99, 99.99) used by some catalogs.
        phot_bad |= (phot_values < 0) | (phot_values > MAX_VALID_MAG)

        # Errors that are bad; i.e. the photometry is an upper limit
        err_bad = np.zeros(len(catalog), dtype=bool)
        if err_key is not None and err_key in catalog.colnames and _is_numeric_column(catalog[err_key]):
            err_values = _column_values(catalog[err_key])
            err_bad = ~np.isfinite(err_values)

            # This is key. A zero error is unphysical and is bad too.
            err_bad |= (err_values <= 0) | (err_values > 5)
        combined_bad = phot_bad | err_bad

        # No bad values? Skip to next key.
        if not np.any(combined_bad):
            continue

        # Mask bad photometry and paired errors, then fill with sentinel value.
        catalog[phot_key][phot_bad] = fill_mask

        # Mask bad errors and also mask errors corresponding to bad photometry.
        if err_key is not None and err_key in catalog.colnames and _is_numeric_column(catalog[err_key]):
            catalog[err_key][combined_bad] = fill_mask

    return catalog

def fill_masked(table: Table, fill_value: int | float,
                str_fill: str | None = None) -> Table:
    """
    Fill the masked entries of a table, column by column, without damaging
    non-numeric columns.

    ``Table.filled(<number>)`` casts the number to the dtype of every masked
    column, which truncates the fill value in narrow string columns
    (``'-99.0'`` becomes ``'-9'`` in a 2-character column), puts a float in
    string columns of dtype object, turns masked booleans into True and
    raises an error if the value does not fit (e.g. -99 in an unsigned
    integer column). This function instead fills:

    - numeric columns with ``fill_value``;
    - string and bytes columns with the text of the fill value (or
      ``str_fill``), after widening the column so that the text fits;
    - object columns with the same text;
    - and leaves masked any column that cannot hold the value, i.e. booleans,
      unsigned integers that cannot represent it, and any other dtype.

    Args:
        table (astropy.table.Table): Table with masked entries. It is not
            modified.
        fill_value (int or float): Value used for the masked entries of
            numeric columns.
        str_fill (str, optional): Text used for the masked entries of string
            columns. Defaults to ``str(fill_value)`` (e.g. '-99.0'), which
            keeps the fill parsable as a number.

    Returns:
        astropy.table.Table: A copy of ``table`` (with its metadata) in which
        the masked entries have been filled. It has no masked entries left
        unless some column could not hold the fill.

    """
    text = str(fill_value) if str_fill is None else str_fill
    out = table.copy()
    for name in out.colnames:
        col = out[name]
        if not isinstance(col, MaskedColumn) or not np.any(col.mask):
            continue
        kind = col.dtype.kind
        if kind in 'fiu':
            try:
                newcol = col.filled(fill_value)
            except (TypeError, ValueError, OverflowError):
                continue  # The value does not fit in this dtype
        elif kind in 'US':
            nbytes = 4 if kind == 'U' else 1
            width = max(col.dtype.itemsize // nbytes, len(text))
            col = col.astype(f'{kind}{width}')
            newcol = col.filled(text if kind == 'U' else text.encode())
        elif kind == 'O':
            newcol = col.filled(text)
        else:
            continue  # bool, datetime, ...: no meaningful numeric sentinel
        out.replace_column(name, newcol)
    # An unmasked table is returned if everything could be filled
    if not out.has_masked_values:
        out = Table(out, masked=False)
    return out


def clean_cat(catalog: Table, pdict: dict, fill_mask: int | float | None = None,
              mask_photometry: bool = False) -> Table:
    """
    Convert table column names intrinsic to the slurped
    catalog with the FRB survey desired values

    The two optional arguments combine as follows:

    ============ ================ ===========================================
    fill_mask    mask_photometry  Result
    ============ ================ ===========================================
    None         False            Columns are only renamed; masks are kept
    None         True             Bad photometry is replaced by -99.; other
                                  masked entries stay masked
    a value      False            All masked entries are replaced by the value
    a value      True             Bad photometry is replaced by the value,
                                  then so are all other masked entries
    ============ ================ ===========================================

    Args:
        catalog (astropy.table.Table): Catalog generated by astroquery
        pdict (dict):  Defines the original key and desired key
        fill_mask (int or float, optional): Fill value for masked items.
            If None (default), masked items are not filled. String columns
            are filled with the text of the value (see :func:`fill_masked`).
        mask_photometry (bool, optional): Mask invalid photometric values and
            paired errors (replacing them with ``fill_mask``, or -99. if that
            is None) before returning the catalog.

    Returns:
        astropy.table.Table:  modified catalog

    """
    for key,value in pdict.items():
        if value in catalog.keys():
            catalog.rename_column(value, key)
    if mask_photometry:
        sentinel = -99.0 if fill_mask is None else fill_mask
        catalog = _mask_bad_photometry(catalog, pdict, fill_mask=sentinel)
    # Fill any masked items
    if fill_mask is not None and catalog.mask is not None:
        catalog = fill_masked(catalog, fill_mask)
    return catalog


def ensure_empty_schema(catalog: Table, columns: list[str],
                        dtypes: dict[str, type | str | np.dtype] | None = None) -> Table:
    """
    Ensure empty catalogs keep a standardized column schema.

    This mirrors the 2MASS pattern where the output remains an empty table
    with survey-standard columns instead of becoming columnless.
    The table is modified in place.

    Args:
        catalog (astropy.table.Table): Catalog to standardize. Catalogs with
            one or more rows are returned untouched.
        columns (list of str): Names of the columns an empty catalog should
            have. Missing columns are added as empty columns and all
            other columns are dropped.
        dtypes (dict, optional): Maps column names to the dtype (anything
            ``numpy.dtype`` accepts, e.g. ``int``, ``str`` or 'uint64') of the
            columns that are not floats. Columns not in the dictionary are
            floats. Columns that are already in the empty catalog are
            converted if their kind of dtype (float, integer, string, ...)
            differs, so that empty and non-empty catalogs of a survey agree.

    Returns:
        astropy.table.Table: ``catalog``, with exactly the columns in
        ``columns`` if it was empty.

    """
    if len(catalog) != 0:
        return catalog

    dtypes = {} if dtypes is None else dtypes
    for col in columns:
        dtype = np.dtype(dtypes.get(col, float))
        if col not in catalog.colnames:
            catalog[col] = np.array([], dtype=dtype)
        elif catalog[col].dtype.kind != dtype.kind:
            catalog[col] = catalog[col].astype(dtype)
    catalog.keep_columns(list(columns))
    return catalog


def normalize_catalog(catalog: Table, coord: SkyCoord, radius: units.Quantity,
                      survey_name: str, radec: tuple[str, str] | None = None,
                      add_sep: bool = True) -> Table:
    """
    Normalize survey catalog to enforce uniform output contract.

    Ensures:
    - Lowercase 'ra', 'dec' coordinate columns
    - Required metadata keys: 'radius', 'survey'
    - 'separation' column in arcmin (for non-empty catalogs)

    Args:
        catalog (astropy.table.Table): Input catalog (may be empty)
        coord (astropy.coordinates.SkyCoord): Reference coordinate
        radius (astropy.units.Quantity): Search radius
        survey_name (str): Survey name for metadata
        radec (tuple of str, optional): Original (RA, DEC) column names.
            If None, auto-detects.
        add_sep (bool, optional): Add separation column for non-empty catalog

    Returns:
        astropy.table.Table: Normalized catalog

    Raises:
        ValueError: If the RA/DEC columns cannot be found in a non-empty
            catalog.

    """
    # Empty catalogs may legitimately have no coordinate columns.
    # Set required metadata and optional empty separation, then return.
    if len(catalog) == 0:
        catalog.meta['survey'] = survey_name
        catalog.meta['radius'] = radius
        if add_sep and 'separation' not in catalog.colnames:
            catalog['separation'] = units.Quantity([], unit=units.arcmin)
        return catalog

    # Auto-detect RA/DEC column names if not provided
    if radec is None:
        # Try common variations
        ra_col = None
        dec_col = None
        for candidate in ['ra', 'RA', 'Ra', 'rA', 'RAJ2000', 'ALPHAJ_2000']:
            if candidate in catalog.colnames:
                ra_col = candidate
                break
        for candidate in ['dec', 'DEC', 'Dec', 'dEC', 'DECJ2000', 'DEJ2000', 'DELTAJ_2000']:
            if candidate in catalog.colnames:
                dec_col = candidate
                break
        
        if ra_col is None or dec_col is None:
            raise ValueError("Cannot find RA/DEC columns in catalog. Please specify radec parameter.")
        radec = (ra_col, dec_col)
    
    # Rename RA/DEC to lowercase if needed
    if radec[0] != 'ra' and radec[0] in catalog.colnames:
        catalog.rename_column(radec[0], 'ra')
    if radec[1] != 'dec' and radec[1] in catalog.colnames:
        catalog.rename_column(radec[1], 'dec')
    
    # Ensure ra, dec exist after normalization
    if 'ra' not in catalog.colnames or 'dec' not in catalog.colnames:
        raise ValueError("Catalog must have 'ra' and 'dec' columns after normalization")
    
    # Set required metadata
    catalog.meta['survey'] = survey_name
    catalog.meta['radius'] = radius
    
    # Add separation for non-empty catalogs
    if len(catalog) > 0 and add_sep:
        if 'separation' not in catalog.colnames:
            catalog = sort_by_separation(catalog, coord, radec=('ra', 'dec'), add_sep=True)
        # Ensure separation has arcmin units; handle legacy/unitless columns.
        sep_unit = getattr(catalog['separation'], 'unit', None)
        if sep_unit is None:
            catalog['separation'] = units.Quantity(np.asarray(catalog['separation']), unit=units.arcmin)
        elif units.Unit(sep_unit).is_equivalent(units.arcmin):
            catalog['separation'] = catalog['separation'].to(units.arcmin)
        else:
            # Incompatible legacy values: recompute from coordinates.
            catalog = sort_by_separation(catalog, coord, radec=('ra', 'dec'), add_sep=True)
    elif len(catalog) == 0 and add_sep:
        # For empty catalogs, add empty separation column to maintain consistency
        catalog['separation'] = units.Quantity([], unit=units.arcmin)
    
    return catalog


def sort_by_separation(catalog: Table, coord: SkyCoord,
                       radec: tuple[str, str] = ('ra', 'dec'),
                       add_sep: bool = True) -> Table:
    """
    Sort an input catalog by separation from input coordinate

    Args:
        catalog (astropy.table.Table):  Table of sources
        coord (astropy.coordinates.SkyCoord): Reference coordinate for sorting
        radec (tuple of str, optional): Defines catalog columns holding
            RA, DEC (in deg)
        add_sep (bool, optional): Add a 'separation' column with units of arcmin

    Returns:
        astropy.table.Table: Sorted catalog

    Raises:
        IOError: If either of the ``radec`` columns is not in ``catalog``.

    """
    # Check
    for key in radec:
        if key not in catalog.keys():
            print("RA/DEC key: {:s} not in your Table".format(key))
            raise IOError("Try again..")
    # Grab coords
    cat_coords = SkyCoord(ra=catalog[radec[0]].data,
                          dec=catalog[radec[1]].data, unit='deg')

    # Separations
    seps = coord.separation(cat_coords)
    isrt = np.argsort(seps)
    # Add?
    if add_sep:
        catalog['separation'] = seps.to('arcmin')
    # Sort
    srt_catalog = catalog[isrt]
    # Return
    return srt_catalog


def match_ids(IDs: np.ndarray, match_IDs: np.ndarray,
              require_in_match: bool = True) -> np.ndarray:
    """ Match input IDs to another array of IDs (usually in a table)
    Return the rows aligned with input IDs

    Args:
        IDs (ndarray): ID values to match
        match_IDs (ndarray):  ID values to match to
        require_in_match (bool, optional): Require that each of the
          input IDs occurs within the match_IDs

    Returns:
        ndarray: Rows in match_IDs that match to IDs, aligned -1 if there is no match

    Raises:
        IOError: If ``require_in_match`` is True and any of ``IDs`` is
            not in ``match_IDs``.

    """
    rows = -1 * np.ones_like(IDs).astype(int)
    # Find which IDs are in match_IDs
    in_match = np.isin(IDs, match_IDs)
    if require_in_match:
        if np.sum(~in_match) > 0:
            raise IOError("qcat.match_ids: One or more input IDs not in match_IDs")
    rows[~in_match] = -1
    #
    IDs_inmatch = IDs[in_match]
    # Find indices of input IDs in meta table -- first instance in meta only!
    xsorted = np.argsort(match_IDs)
    ypos = np.searchsorted(match_IDs, IDs_inmatch, sorter=xsorted)
    indices = xsorted[ypos]
    rows[in_match] = indices
    return rows


def summarize_catalog(frbc: dict, catalog: Table, summary_radius: Angle,
                      photom_column: str, magnitude: bool) -> list[str]:
    """
    Generate simple text describing the sources from
    an input catalog within a given radius

    Args:
        frbc (dict): FRB Candidate object. Must provide the candidate's
            position as ``frbc['coord']`` (astropy.coordinates.SkyCoord)
        catalog (astropy.table.Table): Catalog table. Must have 'ra' and 'dec'
            columns (in deg), the ``photom_column`` column, and
            ``catalog.meta['survey']``
        summary_radius (astropy.coordinates.Angle):  Radius to summarize on
        photom_column (str): Column specifying which flux to work on
        magnitude (bool): Is the flux a magnitude?

    Returns:
        list of str: List of comments on the catalog

    """
    # Init
    summary_list = []
    coords = SkyCoord(ra=catalog['ra'], dec=catalog['dec'], unit='deg')
    # Find all within the summary radius
    seps = frbc['coord'].separation(coords)
    in_radius = seps < summary_radius
    # Start summarizing
    summary_list += ['{:s}: There are {:d} source(s) within {:0.1f} arcsec'.format(
        catalog.meta['survey'], np.sum(in_radius), summary_radius.to('arcsec').value)]
    # If any found
    if np.any(in_radius):
        # Brightest
        if magnitude:
            brightest = np.argmin(catalog[photom_column][in_radius])
        else:
            brightest = np.argmax(catalog[photom_column][in_radius])
        summary_list += ['{:s}: The brightest source has {:s} of {:0.2f}'.format(
            catalog.meta['survey'], photom_column,
            catalog[photom_column][in_radius][brightest])]
        # Closest
        closest = np.argmin(seps[in_radius])
        summary_list += ['{:s}: The closest source is at separation {:0.2f} arcsec and has {:s} of {:0.2f}'.format(
            catalog.meta['survey'],
            seps[in_radius][closest].to('arcsec').value,
            photom_column, catalog[photom_column][in_radius][closest])]
    # Return
    return summary_list


def xmatch_catalogs(cat1: Table, cat2: Table,
                    dist: units.Quantity = 5*units.arcsec,
                    RACol1: str = "ra", DecCol1: str = "dec",
                    RACol2: str = "ra", DecCol2: str = "dec",
                    distcol1: str | None = None, distcol2: str | None = None,
                    return_match_idx: bool = False) -> tuple:
    """
    Cross matches two astronomical catalogs and returns
    the matched tables.

    Args:
        cat1 (astropy.table.Table): First table with sky coordinates to be
            matched.
        cat2 (astropy.table.Table): Second table with sky coordinates to be
            matched.
        dist (astropy.units.Quantity, optional): Maximum separation for a
            valid match. 5 arcsec by default. Can be length units
            if distcol1 and distcol2 are provided.
        RACol1 (str, optional): Name of the column in cat1 that contains
            RA in degrees.
        DecCol1 (str, optional): Name of the column in cat1 that contains
            Dec in degrees.
        RACol2 (str, optional): Name of the column in cat2 that contains
            RA in degrees.
        DecCol2 (str, optional): Name of the column in cat2 that contains
            Dec in degrees.
        distcol1 (str, optional): Name of the column in cat1 that contains
            the radial distance as floats in Mpc. If None (or if distcol2
            is None), 2D cross-matches are returned.
        distcol2 (str, optional): Name of the column in cat2 that contains
            the radial distance as floats in Mpc. If None (or if distcol1
            is None), 2D cross-matches are returned.
        return_match_idx (bool, optional): Return the match indices and
            separations for every row of cat1 instead of the matched tables.

    Returns:
        tuple: If ``return_match_idx`` is False, ``(match1, match2)``, the
        astropy Tables of matched rows from cat1 and cat2. Otherwise,
        ``(idx, d2d, d3d)``: the indices into cat2 of the nearest neighbor
        of each cat1 entry (ndarray), and the on-sky (Angle) and 3D
        (Distance, or dimensionless if no distances were given) separations
        to go with them.

    """
    assert isinstance(cat1, (Table, QTable))&isinstance(cat2, (Table, QTable)), "Catalogs must be astropy Table instances."
    assert (RACol1 in cat1.colnames)&(DecCol1 in cat1.colnames), " Could not find either {:s} or {:s} in cat1".format(RACol1, DecCol1)
    assert (RACol2 in cat2.colnames)&(DecCol2 in cat2.colnames), " Could not find either {:s} or {:s} in cat2".format(RACol2, DecCol2)
    do_3d = (distcol1 is not None)&(distcol2 is not None)
    if do_3d:
        assert (distcol1 in cat1.colnames)&(distcol2 in cat2.colnames), "Could not find either {:s} or {:s} in cat1".format(distcol1, distcol2)
        dist1 = cat1[distcol1]
        dist2 = cat2[distcol2]
        if getattr(dist1, 'unit', None) is None:
            dist1 = dist1 * units.Mpc
        else:
            dist1 = dist1.to(units.Mpc)
        if getattr(dist2, 'unit', None) is None:
            dist2 = dist2 * units.Mpc
        else:
            dist2 = dist2.to(units.Mpc)
    else:
        dist1 = None
        dist2 = None
    # Get coordinates
    ra1 = cat1[RACol1]
    dec1 = cat1[DecCol1]
    ra2 = cat2[RACol2]
    dec2 = cat2[DecCol2]

    if getattr(ra1, 'unit', None) is None:
        ra1 = ra1 * units.deg
    else:
        ra1 = ra1.to(units.deg)
    if getattr(dec1, 'unit', None) is None:
        dec1 = dec1 * units.deg
    else:
        dec1 = dec1.to(units.deg)
    if getattr(ra2, 'unit', None) is None:
        ra2 = ra2 * units.deg
    else:
        ra2 = ra2.to(units.deg)
    if getattr(dec2, 'unit', None) is None:
        dec2 = dec2 * units.deg
    else:
        dec2 = dec2.to(units.deg)

    cat1_coord = SkyCoord(ra1, dec1, distance=dist1)
    cat2_coord = SkyCoord(ra2, dec2, distance=dist2)

    # Match 2D
    idx, d2d, d3d = cat1_coord.match_to_catalog_sky(cat2_coord)

    # Get matched tables
    if do_3d:
        separation = d3d
    else:
        separation = d2d
    match1 = cat1[separation < dist]
    match2 = cat2[idx[separation < dist]]

    if return_match_idx:
        return idx, d2d, d3d
    else:
        return match1, match2


def _detect_mag_cols(photometry_table: Table) -> tuple[list[str], list[str]]:
    """
    Searches the column names of a 
    photometry table for columns with mags.

    Args:
        photometry_table (astropy.table.Table): A table containing
            photometric data from a catalog.

    Returns:
        tuple: Two lists of str:

            - mag_colnames: column names with magnitudes
            - mag_err_colnames: column names with errors in the magnitudes
    """
    assert type(photometry_table)==Table, "Photometry table must be an astropy Table instance."
    allcols = photometry_table.colnames
    photom_cols = np.array(valid_filters)
    photom_errcols = np.array([filt+"_err" for filt in photom_cols])

    photom_cols = photom_cols[[elem in allcols for elem in photom_cols]]
    photom_errcols = photom_errcols[[elem in allcols for elem in photom_errcols]]
    
    return photom_cols.tolist(), photom_errcols.tolist()


def mag_from_flux(flux: units.Quantity,
                  flux_err: units.Quantity | None = None
                  ) -> tuple[float | np.ndarray, float | np.ndarray | None]:
    """
    Get the AB magnitude from a flux

    Args:
        flux (astropy.units.Quantity): Flux, in any units convertible
            to Jy
        flux_err (astropy.units.Quantity, optional): Error in flux

    Returns:
        tuple: ``(mag, mag_err)``, floats (or ndarrays if the inputs are
        arrays) holding the AB magnitude and its error.
        ``mag_err`` is None if ``flux_err`` is None.

    """
    # convert flux to Jansky
    flux_Jy = flux.to('Jy').value

    # get mag
    mag_AB = -2.5*np.log10(flux_Jy) + 8.9

    # get error
    if flux_err is not None:
        flux_Jy_err = flux_err.to('Jy').value
        err_mag2 = (-2.5/np.log(10.) / flux_Jy)**2 * flux_Jy_err**2
        err_mag = np.sqrt(err_mag2)
    else:
        err_mag = None
    return mag_AB, err_mag

def _mags_to_flux(mag: Column, zpt_flux: units.Quantity = 3630.7805*units.Jy,
                  mag_err: Column | None = None, exact_mag_err: bool = False
                  ) -> Column | tuple[Column, Column]:
    """
    Convert a magnitude to flux (in the same units as ``zpt_flux.value``)

    Bad magnitudes (<0 or >``MAX_VALID_MAG``, i.e. 35) and bad magnitude errors (<=0 or >5) are
    set to -99. in the output. The error of a bad magnitude is also set to -99.
    An error of 999 (the upper limit flag of the host photometry) is a bad
    error, so the flux of an upper limit is kept and its error set to -99.

    Args:
        mag (astropy.table.Column): magnitude
        zpt_flux (astropy.units.Quantity, optional): Zero point flux for the
            magnitude. Assumes AB mags by default
            (i.e. zpt_flux = 3630.7805 Jy). 
        mag_err (astropy.table.Column, optional): uncertainty in magnitude
        exact_mag_err (bool, optional): True if you are aware that the mag
            error were estimated exactly and not using a first order (in SNR)
            approximation. 

    Returns:
        astropy.table.Column or tuple: ``flux``, the flux (in Jy for the
        default ``zpt_flux``), if ``mag_err`` is None. Otherwise
        ``(flux, flux_err)``, both Columns.

    """
    # Data validation -- check for Jy
    assert (type(zpt_flux) == units.Quantity)*(zpt_flux.decompose().unit == units.kg/units.s**2), "zpt_flux units should be Jy or with dimensions kg/s^2."

    # Prepare output column
    flux = mag.copy()

    # Convert fluxes
    badmags = (mag<0) | (mag>MAX_VALID_MAG)
    flux[badmags] = -99.
    flux[~badmags] = zpt_flux.value*10**(-mag[~badmags]/2.5)
    
    if mag_err is not None:
        flux_err = mag_err.copy()
        # An error is bad if it is itself bad (this includes the 999 upper
        # limit flag) or if the magnitude it belongs to is bad.
        baderrs = (mag_err <= 0) | (mag_err > 5) | badmags
        flux_err[baderrs] = -99.
        if exact_mag_err:
            flux_err[~baderrs] = flux[~baderrs]*(10**(mag_err[~baderrs]/2.5)-1) # exact error
        else:
            flux_err[~baderrs] = np.log(10)/2.5*flux[~baderrs]*mag_err[~baderrs] # first order approximation
        return flux, flux_err
    else:
        return flux    

def convert_mags_to_flux(photometry_table: Table, fluxunits: str = 'mJy',
                         exact_mag_err: bool = False) -> Table:
    """
    Takes a table of photometric measurements
    in mags and converts it to flux units.

    ..todo..   NEED TO ADD DOCS ON VISTA, ETC..

    Args:
        photometry_table (astropy.table.Table):
            A table containing photometric
            data from a catlog.
        fluxunits (str, optional):
            Flux units to convert the magnitudes
            to, as parsed by astropy.units. Default is mJy.
        exact_mag_err (bool, optional):
            Use if you know that the mag errors were estimated
            exactly as opposed to the first-order approximation
            that is usually quoted.

    Returns:
        astropy.table.Table: `photometry_table` but the magnitudes
        are converted to fluxes. A magnitude without an error column
        (``<filter>_err``) is converted on its own.
        For upper limits, the flux is the 3sigma value and
        the error is set to -99.

    """
    fluxtable = photometry_table.copy()
    # Find columns with magnitudes based on filter names
    mag_cols, mag_errcols = _detect_mag_cols(fluxtable)
    convert = units.Jy.to(fluxunits)

    for mag in mag_cols:
        # Pair the magnitude with its own error column, if it has one.
        # (The two lists are not aligned when a magnitude lacks an error.)
        err = mag+"_err" if mag+"_err" in mag_errcols else None
        if err is None:
            flux = _mags_to_flux(photometry_table[mag])
        else:
            flux, flux_err = _mags_to_flux(photometry_table[mag],
                                           mag_err=photometry_table[err],
                                           exact_mag_err=exact_mag_err)

        # Allow for bad flux values
        badflux = flux == -99.0
        fluxtable[mag][badflux] = flux[badflux]
        fluxtable[mag][~badflux] = flux[~badflux]*convert

        # Allow for bad errors
        if err is not None:
            baderr = flux_err == -99.0
            fluxtable[err][baderr] = flux_err[baderr]
            fluxtable[err][~baderr] = flux_err[~baderr]*convert

    return fluxtable

def remove_duplicates(tab:Table, idcol:str)->Table:
    """
    In an astropy table if there are duplicate
    entries, remove the duplicates. Generally,
    these will be duplicate objects (i.e. multiple
    observations of same object ID or the same
    entry repeated multiple times from cross-matching.)

    Args:
        tab (astropy.table.Table): A table of entries.
        idcol (str): A column name that has unique ids
            for each table entry.

    Returns:
        astropy.table.Table: A table with only the unique ids,
        sorted by ``idcol``.

    """
    unique_tab = tab.copy()
    assert isinstance(unique_tab, Table), "Please provide an astropy table."
    assert isinstance(idcol, str), "Please provide a valid column name."
    assert idcol in tab.colnames, "{} not a column in the given table".format(idcol)
    # Sort entries first.
    unique_tab.sort(idcol)
    # Get the duplicates.
    duplicate_ids = np.where(unique_tab[1:][idcol]==unique_tab[:-1][idcol])[0]+1
    unique_tab.remove_rows(duplicate_ids)
    return unique_tab
    
def xmatch_and_merge_cats(tab1: Table, tab2: Table,
                          tol: units.Quantity = 1*units.arcsec,
                          table_names: tuple[str, str] = ('1', '2'),
                          fill_value: int | float | None = None,
                          **kwargs) -> Table:
    """
    Given two source catalogs, cross-match and merge them. This function 
    ensures there is a unique match between tables as opposed to the default join_skycoord
    behavior which matches multiple objects on the right table to
    a source on the left. The two tables must contain the columns 'ra' and 'dec' (case-sensitive).

    Args:
        tab1 (astropy.table.Table): First photometry catalog. Must contain
            columns named ra and dec.
        tab2 (astropy.table.Table): Second photometry catalog. Must contain
            columns named ra and dec.
        tol (astropy.units.Quantity, optional): Maximum angular separation
            for cross-matching.
        table_names (tuple of str, optional): Names of the two tables for
            naming unique columns in the merged table.
        fill_value (int or float, optional): Value used to fill the entries
            of sources that are in only one of the tables. If None (default),
            those entries stay masked. Use -999. to follow the convention of
            :mod:`frb.galaxies.defs` for photometry that was not measured.
            String columns are filled with the text of the value
            (see :func:`fill_masked`).
        **kwargs: Additional keyword arguments to be passed onto
            xmatch_catalogs

    Returns:
        astropy.table.Table: Merged catalog. It has masked entries for
        the sources that are in only one of the tables, unless ``fill_value``
        is given.

    """
    if table_names is not None:
        assert len(table_names)==2, "Invalid number of table names for two tables."
        assert (type(table_names[0])==str)&(type(table_names[1])==str), "Table names should be strings."
    
    assert np.all(np.isin(['ra','dec'],tab1.colnames)), "Table 1 doesn't have column 'ra' and/or 'dec'."
    assert np.all(np.isin(['ra','dec'],tab2.colnames)), "Table 2 doesn't have column 'ra' and/or 'dec'."

    # Edge cases: zero length tables
    if len(tab1) == 0:
        return tab2.copy()
    elif len(tab2) == 0:
        return tab1.copy()

    # Cross-match tables for tab1 INTERSECTION tab2.
    matched_tab1, matched_tab2 = xmatch_catalogs(tab1, tab2, tol, **kwargs)

    # tab1 INTERSECTION tab2
    inner_join = hstack([matched_tab1, matched_tab2],
                        table_names=table_names)
    # Remove unnecessary ra/dec columns and rename remaining coordinate
    # columns corectly. 
    tab1_coord_cols = ['ra_'+table_names[0],"dec_"+table_names[0]]
    tab2_coord_cols = ['ra_'+table_names[1],"dec_"+table_names[1]]


    inner_join.remove_columns(tab2_coord_cols)
    inner_join.rename_columns(tab1_coord_cols, ['ra', 'dec'])

    # Now get all objects that weren't matched.
    if len(matched_tab1) == 0:
        not_matched_tab1 = tab1
        not_matched_tab2 = tab2
    else:
        not_matched_tab1 = tab1[~np.isin(tab1, matched_tab1)]
        not_matched_tab2 = tab2[~np.isin(tab2, matched_tab2)]

    # (tab1 UNION tab2) - (tab1 INTERSECTION tab2)

    # Are there unmatched entries in both tables?
    if (len(not_matched_tab1)!=0)&(len(not_matched_tab2)!=0):
        outer_join = join(not_matched_tab1, not_matched_tab2,
                    keys=['ra','dec'], join_type='outer', table_names=table_names)
        merged = vstack([inner_join, outer_join])
    # Only table 1 has unmatched entries?
    elif (len(not_matched_tab1)!=0)&(len(not_matched_tab2)==0):
        merged = vstack([inner_join, not_matched_tab1])
    # Only table 2?
    elif (len(not_matched_tab1)==0)&(len(not_matched_tab2)!=0):
        merged = vstack([inner_join, not_matched_tab2])
    # Neither?
    else:
        merged = inner_join
    # Final cleanup. Just in case.
    weird_cols = np.isin(['ra_1','dec_1','ra_2','dec_2'],merged.colnames)
    if np.any(weird_cols):
        merged.remove_columns(np.array(['ra_1','dec_1','ra_2','dec_2'])[weird_cols])
    # Fill and return.
    if fill_value is not None:
        merged = fill_masked(merged, fill_value)
    return merged
    
    '''
    TODO: Write this function once CDS starts working again (through astroquery) 
    def xmatch_gaia(catalog,max_sep = 5*u.arcsec,racol='ra',deccol='dec'):
        """
        Cross match against Gaia DR2
        and return the cross matched table.
        Args:
            max_sep (Angle): maximum separation to be
                            considered a valid match.
        Returns:
            xmatch_tab (Table): a table with corss matched
                                entries.
        """
    ''' 