name: CI Tests

on:
  push:
    branches:
    - master
  pull_request:

env:
  SETUP_XVFB: True  # avoid issues if something tries to open a GUI window

jobs:
  ci-tests:
    name: Tox env ${{ matrix.python }}-${{ matrix.toxenv }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ['3.11', '3.12']
        toxenv: [test, test-astropydev]
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install base dependencies
      run: |
        python -m pip install -r frb/requirements.txt --upgrade pip tox
        python -m pip install git+https://github.com/FRBs/ne2001.git#egg=ne2001
        python -m pip install git+https://github.com/FRBs/astropath.git#egg=astropath
        python -m pip install git+https://github.com/linetools/linetools#egg=linetools
    - name: Test with tox
      run: |
        tox -e ${{ matrix.python }}-${{ matrix.toxenv }}
